// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm05plXMk3wl2gOgVnlCmahuczSjmw_4Q',
    appId: '1:253231283087:web:d987ba630d1e198d6b69fa',
    messagingSenderId: '253231283087',
    projectId: 'faym-assignment',
    authDomain: 'faym-assignment.firebaseapp.com',
    storageBucket: 'faym-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxjcGMeG-_VRyua6bC2vLEUPYj56XHO5s',
    appId: '1:253231283087:android:4802f8e609623ca96b69fa',
    messagingSenderId: '253231283087',
    projectId: 'faym-assignment',
    storageBucket: 'faym-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUAMHe7uBSXuYP5Q3bZ58VReYvm6VSqo',
    appId: '1:253231283087:ios:b6508ab2c98fae696b69fa',
    messagingSenderId: '253231283087',
    projectId: 'faym-assignment',
    storageBucket: 'faym-assignment.appspot.com',
    iosBundleId: 'com.example.faym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUAMHe7uBSXuYP5Q3bZ58VReYvm6VSqo',
    appId: '1:253231283087:ios:aa28fb27636ccb8d6b69fa',
    messagingSenderId: '253231283087',
    projectId: 'faym-assignment',
    storageBucket: 'faym-assignment.appspot.com',
    iosBundleId: 'com.example.faym.RunnerTests',
  );
}
